version: 0.2

phases:
  pre_build:
    commands:
       - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 047590332772.dkr.ecr.eu-central-1.amazonaws.com
       - REPOSITORY_URI=047590332772.dkr.ecr.eu-central-1.amazonaws.com/cars-models-service-2022
       - IMAGE_TAG=$(echo $(echo $VERSION)'.'$CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - docker build --build-arg SECRET_ID=$(echo $SECRET_ID) --build-arg API_ENV=$(echo $API_ENV) --build-arg API_HOST=$(echo $API_HOST) --build-arg PORT=$(echo $PORT) --build-arg GITHUB_TOKEN=$(echo $GITHUB_TOKEN) --build-arg AWS_REGION=$(echo $AWS_REGION) -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
       - docker push $REPOSITORY_URI:$IMAGE_TAG